#:schema node_modules/wrangler/config-schema.json
name = "goodreads-books-rec"
main = "src/index.js"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

# [[vectorize]]
# binding = "VECTORIZE_INDEX" 
# index_name = "goodreads" #doesn't populate

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "goodreads1024" # works for populating, VECTOR_QUERY_ERROR (code = 40006): invalid query vector, expected 1024 dimensions, and got 768 dimensions

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "goodreads-db"
database_id = "389cd05d-455a-4de7-b6a5-167fa3058cc6"

[[queues.producers]]
binding = "POPULATE_QUEUE"
queue = "populate-queue"